name: Signup

on:
  push:
    branches:
      - 'master'

# on:
#   schedule:
#     - cron: "0 13 * * 3" # Wednesday -> Monday
#     - cron: "0 13 * * 4" # Thursday -> Tuesday
#     # - cron: "0 13 * * 5" # Friday -> Wednesday (Rest day)
#     - cron: "0 13 * * 6" # Saturday -> Thursday
#     - cron: "0 13 * * 7" # Sunday -> Friday

jobs:
  signup:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/wodify/**/*
        env:
          CYPRESS_username: ${{ secrets.BRENNON_USERNAME }}
          CYPRESS_password: ${{ secrets.BRENNON_PW }}